service: aws-node-sqs-worker

frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-offline-sqs

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, dev}
  region: ${opt:stage, us-east-1}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
          Resource:
            - Fn::GetAtt:
                - myQueue
                - Arn

environment: ${file(./env/${self.provider.stage}.yml)}

functions:
  producer:
    handler: handler.producer
    events:
      - http:
          method: post
          path: produce

  consumer:
    handler: handler.consumer
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - myQueue
              - Arn
resources:
  Resources:
    myQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: myQueue

custom:
  serverless-offline-sqs:
    autoCreate: false
    apiVersion: "2012-11-05"
    endpoint: ${env:ELASTICMQ_URL}
    region: ${self:provider:region}
    accessKeyId: na
    secretAccessKey: na
    skipCacheInvalidation: false
