service: aws-node-sqs-worker

frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-offline-sqs

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  environment: ${file(./env/${self:provider.stage}.yml)}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
          Resource:
            - Fn::GetAtt: [myQueue, Arn]

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2012-11-05"
    endpoint: ${self:provider.environment.ELASTICMQ_URL}
    region: ${self:provider.region}
    accessKeyId: ${self:provider.environment.ACCESS_KEY_ID}
    secretAccessKey: ${self:provider.environment.SECRET_ACCESS_KEY}
    skipCacheInvalidation: false

functions:
  producer:
    handler: handler.producer
    events:
      - http:
          method: post
          path: produce

  consumer:
    handler: handler.consumer
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - myQueue
              - Arn
resources:
  Resources:
    myQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: myQueue
