service: aws-node-sqs-worker

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: local

functions:
  producer:
    handler: handler.producer
    events:
      - http:
          method: post
          path: produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

plugins:
  - serverless-offline
  - serverless-offline-sqs
